<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Dinesh" failures="2" tests="4" name="com.DineshCompany.app.HomePageTest" time="45.100" errors="0" timestamp="21 Feb 2021 08:16:34 GMT" skipped="0">
  <testcase classname="com.DineshCompany.app.HomePageTest" name="GetTheTitle" time="9.819"/>
  <testcase classname="com.DineshCompany.app.HomePageTest" name="login" time="8.428">
    <failure message="expected [Dashboard ‹ Wordpress Demo Site at Demo.Center — WordPress] but found [Log In ‹ Wordpress Demo Site at Demo.Center — WordPress]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Dashboard ‹ Wordpress Demo Site at Demo.Center — WordPress] but found [Log In ‹ Wordpress Demo Site at Demo.Center — WordPress]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.DineshCompany.app.HomePageTest.login(HomePageTest.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="com.DineshCompany.app.HomePageTest" name="login" time="11.095">
    <failure message="expected [Dashboard ‹ Wordpress Demo Site at Demo.Center — WordPress] but found [Log In ‹ Wordpress Demo Site at Demo.Center — WordPress]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Dashboard ‹ Wordpress Demo Site at Demo.Center — WordPress] but found [Log In ‹ Wordpress Demo Site at Demo.Center — WordPress]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.DineshCompany.app.HomePageTest.login(HomePageTest.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="com.DineshCompany.app.HomePageTest" name="login" time="15.758"/>
</testsuite> <!-- com.DineshCompany.app.HomePageTest -->
